"""init

Revision ID: df414c9d7c4b
Revises: 
Create Date: 2024-02-22 16:34:24.949970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df414c9d7c4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tokens', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collocations', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='texts_pkey')
    )
    # ### end Alembic commands ###
